FROM node:20-bullseye

# Mediasoup requiere compiladores C++ y Python3 para su worker.
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    build-essential \
    pkg-config \
    net-tools \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./

# Instalamos mediasoup que bajará y compilará su Worker C++ localmente
RUN npm i mediasoup

COPY . .
# En un ambiente real, separaríamos la lógica del worker de mediasoup en un microservicio 
# o entrypoint exclusivo (`worker.js`).
EXPOSE 10000-59999/udp

# Aquí asumo que la instanciación principal también puede inicializar el Worker
CMD ["npm", "run", "start:prod"]
