include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_pub_dependencies: true
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_dynamic_calls: true
    always_use_package_imports: true
    use_build_context_synchronously: true
    lines_longer_than_80_chars: false
